### ISSUE TITLE
How do you create embeddings for FrameNet entities?

### ISSUE THREAD

**Issue by girishponkiya** [DebanjanaKar/GSoC-FrameNetBr#1]
How do you create/learn embeddings for frames, frame elements, and LUs?

It looks like: embedding for an entity name is being considered as an embedding of the entity. Is it correct?

Have you tried any knowledge graph embedding algorithm for the same?

**Comment by DebanjanaKar** [comment]
Apologies for the delayed response. Yes, entity name has been encoded along with it's lexical unit and other features as well. No, we have not explored knowledge graph embeddings in this project.
